export async function seed(knex) {
  await knex('maintenance_rules').del();
  await knex('maintenance_rules').insert([
    // Georgia-adjusted lifespans and 2025 real pricing (sources: docs/RESEARCH.md)
    { system_name: 'hvac', display_name: 'HVAC System', avg_lifespan_years: 12, warning_years_before: 2, critical_years_after: 2, avg_replacement_cost_low: 7000, avg_replacement_cost_high: 12000, group_discount_typical: 0.28, service_type: 'hvac_replacement', is_recurring: false, notes: 'GA climate: 10-15yr lifespan due to humidity + year-round use. Atlanta avg $7.5K-$12K installed.' },
    { system_name: 'water_heater', display_name: 'Water Heater', avg_lifespan_years: 10, warning_years_before: 2, critical_years_after: 2, avg_replacement_cost_low: 1200, avg_replacement_cost_high: 2500, group_discount_typical: 0.35, service_type: 'water_heater', is_recurring: false, notes: 'Atlanta area $1,200-$2,500 installed (tank). Labor ~50% of cost.' },
    { system_name: 'roof', display_name: 'Roof (Asphalt Shingle)', avg_lifespan_years: 20, warning_years_before: 3, critical_years_after: 2, avg_replacement_cost_low: 8000, avg_replacement_cost_high: 20000, group_discount_typical: 0.22, service_type: 'roof_inspection', is_recurring: false, notes: 'GA climate: 15-25yr (UV/heat reduce 20-30%). 2,000-3,000 sqft home: $10K-$13.5K. Architectural shingles $4.50-$6.50/sqft.' },
    { system_name: 'exterior_paint', display_name: 'Exterior Paint', avg_lifespan_years: 7, warning_years_before: 1, critical_years_after: 2, avg_replacement_cost_low: 3500, avg_replacement_cost_high: 8000, group_discount_typical: 0.28, service_type: 'exterior_paint', is_recurring: false, notes: 'GA climate: 5-8yr lifespan. 2,500 sqft home: $5K-$10K. Atlanta avg $1.55-$4.25/sqft. Labor is 70% of cost.' },
    { system_name: 'driveway_sealing', display_name: 'Driveway Sealing', avg_lifespan_years: 3, warning_years_before: 1, critical_years_after: 2, avg_replacement_cost_low: 220, avg_replacement_cost_high: 400, group_discount_typical: 0.35, service_type: 'driveway_sealing', is_recurring: false, notes: 'Asphalt sealcoating 2-car driveway: $220-$360 Atlanta. Concrete sealing: $575-$1,700.' },
    { system_name: 'deck_staining', display_name: 'Deck Stain/Seal', avg_lifespan_years: 3, warning_years_before: 1, critical_years_after: 2, avg_replacement_cost_low: 270, avg_replacement_cost_high: 500, group_discount_typical: 0.30, service_type: 'deck_staining', is_recurring: false, notes: 'GA average $266-$505. Larger decks $550-$1,100.' },
    { system_name: 'garage_door', display_name: 'Garage Door/Opener', avg_lifespan_years: 12, warning_years_before: 2, critical_years_after: 2, avg_replacement_cost_low: 900, avg_replacement_cost_high: 2200, group_discount_typical: 0.20, service_type: 'garage_door', is_recurring: false, notes: 'Atlanta avg $1,074. Single-car from $900, carriage-style $2,200+. Install labor $200-$500.' },
    { system_name: 'gutter_cleaning', display_name: 'Gutter Cleaning', avg_lifespan_years: 1, warning_years_before: 0, critical_years_after: 2, avg_replacement_cost_low: 70, avg_replacement_cost_high: 230, group_discount_typical: 0.35, service_type: 'gutter_cleaning', is_recurring: true, recurrence_months: 12, notes: 'Atlanta avg $134 ($70-$230). $0.75-$3/linear foot. Labor $30-$60/hr.' },
    { system_name: 'pressure_washing', display_name: 'Pressure Washing', avg_lifespan_years: 1, warning_years_before: 0, critical_years_after: 2, avg_replacement_cost_low: 200, avg_replacement_cost_high: 600, group_discount_typical: 0.35, service_type: 'pressure_washing', is_recurring: true, recurrence_months: 12, notes: 'House: $200-$600 (1 story), $500-$1,000 (2 story). Driveway: $160-$270. Avg $310.' },
    { system_name: 'water_heater_flush', display_name: 'Water Heater Flush', avg_lifespan_years: 1, warning_years_before: 0, critical_years_after: 2, avg_replacement_cost_low: 100, avg_replacement_cost_high: 200, group_discount_typical: 0.40, service_type: 'water_heater_flush', is_recurring: true, recurrence_months: 12 },
  ]);
}
